"""model database

Revision ID: 62fba533f72b
Revises: 6eaf085a217c
Create Date: 2020-10-17 08:32:25.493485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fba533f72b'
down_revision = '6eaf085a217c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
