"""init database

Revision ID: 6eaf085a217c
Revises: 4fb4b58a4d4c
Create Date: 2020-10-17 08:05:18.829502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaf085a217c'
down_revision = '4fb4b58a4d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
