"""model database

Revision ID: 800e55fc774a
Revises: 62fba533f72b
Create Date: 2020-10-17 08:34:10.907089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800e55fc774a'
down_revision = '62fba533f72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tahuraevent',
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('judul_event', sa.String(), nullable=False),
    sa.Column('deskripsi_event', sa.Text(), nullable=True),
    sa.Column('gambar_event', sa.String(), nullable=True),
    sa.Column('tanggal_event', sa.DateTime(), nullable=True),
    sa.Column('tanggal_post', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_index(op.f('ix_tahuraevent_id_event'), 'tahuraevent', ['id_event'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tahuraevent_id_event'), table_name='tahuraevent')
    op.drop_table('tahuraevent')
    # ### end Alembic commands ###
