"""change scheme

Revision ID: e49acb792abf
Revises: 800e55fc774a
Create Date: 2020-10-29 21:57:25.221216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49acb792abf'
down_revision = '800e55fc774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
